steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/earapp', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/earapp']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'earapp', '--image', 'gcr.io/$PROJECT_ID/my-app', '--region', 'us-central1', '--platform', 'managed']
images:
- 'gcr.io/$PROJECT_ID/my-app'
